mongodb:
  collection: questions
  credentials:
    authMechanism: SCRAM-SHA-256
    authSource: admin
    password: adminpass
    username: admin
  database: brainers_db
  host: localhost
  port: 27017
rabbitmq:
  credentials:
    password: adminpass
    username: admin
  host: 12.12.12.12
  port: 5678
role: asker
